<?php

namespace HEI\MargeBundle\Repository;

/**
 * ChampSuppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampSuppRepository extends \Doctrine\ORM\EntityRepository
{
}
