<?php

namespace HEI\MargeBundle\Repository;

/**
 * Valeur_defautRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Valeur_defautRepository extends \Doctrine\ORM\EntityRepository
{
}
