# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_CONDUC:       ROLE_USER
    ROLE_DIRECTION:   [ROLE_USER, ROLE_CONDUC]
    ROLE_ADMIN:       [ROLE_USER, ROLE_CONDUC, ROLE_DIRECTION, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          commercial:  { password: userpass, roles: [ 'ROLE_USER' ] }
          conduc:      { password: conducpass, roles: [ 'ROLE_CONDUC' ] }
          direction:   { password: directionpass, roles: [ 'ROLE_DIRECTION' ] }
          admin:       { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
