# app/config/security.yml

security:
  encoders:
    HEI\UserBundle\Entity\User:   sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
#    in_memory:
#      memory:
#        users:
#          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    fos_userbundle:
      id: fos_user.user_provider.username


  firewalls:
#    dev:
#      pattern: ^/(_(profiler|wdt)|css|images|js)/
#      security: false
    main:
      pattern:  ^/
      anonymous:  true
      provider: fos_userbundle
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     %secret%


  access_control:
#    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
