# app/config/security.yml

security:
  encoders:
    HEI\UserBundle\Entity\User:   sha512

  role_hierarchy:
    ROLE_COMMERCIAL:    ROLE_USER
    ROLE_CONDUC:       [ROLE_COMMERCIAL, ROLE_USER]
    ROLE_DIRECTION:    [ROLE_CONDUC, ROLE_COMMERCIAL, ROLE_USER]
    ROLE_ADMIN:        [ROLE_DIRECTION, ROLE_CONDUC, ROLE_COMMERCIAL, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username


  firewalls:
    main:
      pattern:      ^/
      anonymous:    true
      provider:     fos_userbundle
      form_login:
        login_path:   fos_user_security_login
        check_path:   fos_user_security_check
      logout:
        path:         fos_user_security_logout
        target:       fos_user_security_login
      remember_me:
        secret:       %secret%


  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/contact/, role: ROLE_ADMIN }
    - { path: ^/$, role: ROLE_COMMERCIAL}
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/register$, role: ROLE_DIRECTION }