hei_contact_add:
    path:      /add
    defaults:  { _controller: HEIContactBundle:Contact:add }

hei_contact_search:
    path:       /search
    defaults:   { _controller: HEIContactBundle:Contact:search }

hei_contact_consult:
    path:       /consult
    defaults:   { _controller: HEIContactBundle:Contact:consult }

hei_contact_modify:
    path:       /modify
    defaults:   { _controller: HEIContactBundle:Contact:modify }

hei_contact_addComment:
    path:       /addComment
    defaults:   { _controller: HEIContactBundle:Contact:addComment }

hei_file_add:
    path:       /addFile
    defaults:   { _controller: HEIContactBundle:File:add }

hei_file_download:
    path:       /downloadFile
    defaults:   { _controller: HEIContactBundle:File:download }

hei_file_remove:
    path:       /removeFile
    defaults:   { _controller: HEIContactBundle:File:remove }

hei_contact_autocomplete:
    path:       /autocomplete
    defaults:   { _controller: HEIContactBundle:Contact:autocomplete }