services:
    hei.mail_sarbacane:
        class: HEI\ServicesBundle\MailSarbacane\HEIMailSarbacane

    hei.mail_interne:
        class:  HEI\ServicesBundle\MailInterne\HEIMailInterne
        arguments:
            - '@templating'
            - '@mailer'