hei_gestion_users:
    path:     /
    defaults: { _controller: HEIGestionBundle:Gestion:users }

hei_gestion_deleteUser:
    path:     /delete
    defaults: { _controller: HEIGestionBundle:Gestion:delete }
